# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 432b62599a56bbdfa09b794917ff6a33446501f403812f65dc27d4ce1b600155a7233c43e8295f50542542f955ba8ced758bedfbb22ac8d39059de6cea774a69

test:
  secret_key_base: 002e4d357088d86904b3be6da4e2ab16f2e8fa33032322c1312d99455e436efcc36f177606ac927dc035a3a96a02e0ede6bcab62fb0b4e79b44e7cf253385ce4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
